/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package construction.Attendance.QueryPages;

import construction.Attendance.AttendanceQuery;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author faisa
 */

class AttendanceByIDClass{
    int entryNo;
    String date;
    String time;
    String weekday;

    public AttendanceByIDClass(int entryNo, String date, String time, String weekday) {
        this.entryNo = entryNo;
        this.date = date;
        this.time = time;
        this.weekday = weekday;
    }

    public int getEntryNo() {
        return entryNo;
    }

    public String getDate() {
        return date;
    }

    public String getTime() {
        return time;
    }

    public String getWeekday() {
        return weekday;
    }

    public void setEntryNo(int entryNo) {
        this.entryNo = entryNo;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public void setWeekday(String weekday) {
        this.weekday = weekday;
    }
    
    
}

public class AttendanceByID extends javax.swing.JFrame {

    /** Creates new form AttendanceByID */
    public AttendanceByID(AttendanceQuery attendanceQuery,int option,String ID) {
        initComponents();
        
        if(option==1){
            displayAttendanceByIDTable(1,ID);
        }else if(option==2){
            displayAttendanceByIDTable(2,ID);
        }else if(option==3){
            displayAttendanceByIDTable(3,ID);
        }
        setResizable(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
        @Override
        public void windowClosing(WindowEvent event) {
            attendanceQuery.reEnable();
            dispose();
        }
    });
    }
    
    public ArrayList<AttendanceByIDClass> AttendanceIDList(int option,String ID){
        ArrayList<AttendanceByIDClass> attendanceByIDClassesList=new ArrayList<>();
        AttendanceByIDClass attendancedByIDClass;
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection connection = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=Construction;selectMethod=cursor", "sa", "123456");
            String query="select EntryNo,Date,Time,Upper(WeekDay) as Weekday from EngineerAttendance where EngineerID like '"+ID+"'";
            if(option==1){
                query="select EntryNo,Date,Time,Upper(WeekDay) as Weekday from EngineerAttendance where EngineerID like '"+ID+"'";
            }else if(option==2){
                query="select EntryNo,Date,Time,Upper(WeekDay) as Weekday from ArchitectureAttendance where ArchitectureID like '"+ID+"'";
            }else if(option==3){
                query="select EntryNo,Date,Time,Upper(WeekDay) as Weekday from LaborAttendance where LaborID like '"+ID+"'";
            }
            Statement statement = connection.createStatement();
            ResultSet resultSet = statement.executeQuery(query);            
            while (resultSet.next()) {
                
                attendancedByIDClass=new AttendanceByIDClass(resultSet.getInt("EntryNo"),
                        resultSet.getString("Date"),
                        resultSet.getString("Time"),
                        resultSet.getString("Weekday"));                
                attendanceByIDClassesList.add(attendancedByIDClass);
            }        
        }catch (Exception e) {
          JOptionPane.showMessageDialog(null,e);
        }
        return attendanceByIDClassesList;
    }
    
    public void displayAttendanceByIDTable(int option,String date){
        ArrayList<AttendanceByIDClass> list= AttendanceIDList(option,date);
        DefaultTableModel model=(DefaultTableModel)attendanceByIdTable.getModel();
        Object[] row= new Object[4];        
        for(int i=0;i<list.size();i++){
            row[0]=list.get(i).getEntryNo();
            row[1]=list.get(i).getDate();
            row[2]=list.get(i).getTime();
            row[3]=list.get(i).getWeekday();
            model.addRow(row);
        }
        //attendanceTable.enable(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        attendanceByIdTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        attendanceByIdTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "EntryNo", "Date", "Time", "Weekday"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(attendanceByIdTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AttendanceByID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AttendanceByID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AttendanceByID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AttendanceByID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new AttendanceByID().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable attendanceByIdTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
