/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package construction.Attendance.QueryPages;

import construction.Attendance.AttendanceQuery;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author faisa
 */

class RankedByAttendanceClass{
    String ID;
    String name;
    int TotalAttendance;

    public RankedByAttendanceClass(String ID,String name,int TotalAttendance) {
        this.ID = ID;
        this.name=name;
        this.TotalAttendance = TotalAttendance;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
    

    public String getID() {
        return ID;
    }

    public int getTotalAttendance() {
        return TotalAttendance;
    }

    public void setID(String ID) {
        this.ID = ID;
    }

    public void setTotalAttendance(int TotalAttendance) {
        this.TotalAttendance = TotalAttendance;
    }
    
    
}

public class RankedByAttendance extends javax.swing.JFrame {

    /**
     * Creates new form RankedByAttendance
     */
    public RankedByAttendance(AttendanceQuery attendanceQuery,int option) {
        initComponents();
        
        if(option==1){
            displayTable(1);
        }else if(option==2){
            displayTable(2);
        }else if(option==3){
            displayTable(3);
        }
        setResizable(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
        @Override
        public void windowClosing(WindowEvent event) {
            attendanceQuery.reEnable();
            dispose();
        }
    });
    }
    
    public ArrayList<RankedByAttendanceClass> List(int option){
        ArrayList<RankedByAttendanceClass> rankedByAttendanceClassesList=new ArrayList<>();
        RankedByAttendanceClass rankedByAttendanceClass;
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection connection = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=Construction;selectMethod=cursor", "sa", "123456");
            String query="select EngineerID as ID,COUNT(EngineerID) as Count from EngineerAttendance group by EngineerID order by COUNT(EngineerID) desc";
            if(option==1){
                query="select ID,Name,T.Count from Engineer inner join (Select EngineerID as EID,COUNT(EngineerID) as Count from EngineerAttendance group by EngineerID) as T on Engineer.Id=T.EID order by T.Count desc";
            }else if(option==2){
                query="select ID,Name,T.Count from Architecture inner join (Select ArchitectureID as EID,COUNT(ArchitectureID) as Count from ArchitectureAttendance group by ArchitectureID) as T on Architecture.Id=T.EID order by T.Count desc";
            }else if(option==3){
                query="select ID,Name,T.Count from Labor inner join (Select LaborID as EID,COUNT(LaborID) as Count from LaborAttendance group by LaborID) as T on Labor.Id=T.EID order by T.Count desc";
            }
            Statement statement = connection.createStatement();
            ResultSet resultSet = statement.executeQuery(query);            
            while (resultSet.next()) {
                
                rankedByAttendanceClass=new RankedByAttendanceClass(resultSet.getString("ID"),
                        resultSet.getString("Name"),
                        resultSet.getInt("Count"));
                
                rankedByAttendanceClassesList.add(rankedByAttendanceClass);
            }        
        }catch (Exception e) {
          JOptionPane.showMessageDialog(null,e);
        }
        return rankedByAttendanceClassesList;
    }
    
    public void displayTable(int option){
        ArrayList<RankedByAttendanceClass> list= List(option);
        DefaultTableModel model=(DefaultTableModel)rankedByAttendanceTable.getModel();
        Object[] row= new Object[3];        
        for(int i=0;i<list.size();i++){
            row[0]=list.get(i).getID();
            row[1]=list.get(i).getName();            
            row[2]=list.get(i).getTotalAttendance();
            model.addRow(row);
        }
        //attendanceTable.enable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        rankedByAttendanceTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rankedByAttendanceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Total Attendance"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(rankedByAttendanceTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RankedByAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RankedByAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RankedByAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RankedByAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new RankedByAttendance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable rankedByAttendanceTable;
    // End of variables declaration//GEN-END:variables
}
